[2025-06-25T03:08:16.853+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-25T03:08:16.897+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clinlytix360_pipeline.log_dashboard_refresh manual__2025-06-25T03:07:27.304190+00:00 [queued]>
[2025-06-25T03:08:16.910+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clinlytix360_pipeline.log_dashboard_refresh manual__2025-06-25T03:07:27.304190+00:00 [queued]>
[2025-06-25T03:08:16.911+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-06-25T03:08:16.935+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): log_dashboard_refresh> on 2025-06-25 03:07:27.304190+00:00
[2025-06-25T03:08:16.950+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=289) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-25T03:08:16.953+0000] {standard_task_runner.py:63} INFO - Started process 291 to run task
[2025-06-25T03:08:16.951+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'clinlytix360_pipeline', 'log_dashboard_refresh', 'manual__2025-06-25T03:07:27.304190+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/clinlytix_dag.py', '--cfg-path', '/tmp/tmprczt_m9c']
[2025-06-25T03:08:16.957+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask log_dashboard_refresh
[2025-06-25T03:08:17.089+0000] {task_command.py:426} INFO - Running <TaskInstance: clinlytix360_pipeline.log_dashboard_refresh manual__2025-06-25T03:07:27.304190+00:00 [running]> on host 34096c58d0ef
[2025-06-25T03:08:17.292+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ajayc' AIRFLOW_CTX_DAG_ID='clinlytix360_pipeline' AIRFLOW_CTX_TASK_ID='log_dashboard_refresh' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T03:07:27.304190+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T03:07:27.304190+00:00'
[2025-06-25T03:08:17.300+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-25T03:08:17.303+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-25T03:08:17.305+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Dashboard ready to serve latest data."']
[2025-06-25T03:08:17.339+0000] {subprocess.py:86} INFO - Output:
[2025-06-25T03:08:17.376+0000] {subprocess.py:93} INFO - Dashboard ready to serve latest data.
[2025-06-25T03:08:17.378+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T03:08:17.382+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-25T03:08:17.494+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=clinlytix360_pipeline, task_id=log_dashboard_refresh, execution_date=20250625T030727, start_date=20250625T030816, end_date=20250625T030817
[2025-06-25T03:08:17.582+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-25T03:08:17.635+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-25T03:08:17.640+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
